### PR TITLE
Adding translation into Norwegian

### PR DESCRIPTION
**Pull request by kwillno**

### CODE REVIEW

**Comment by klimeryk** [comment]
Appreciate the PR, @kwillno! I've merged it in https://github.com/klimeryk/recalendar.js/commit/208c51462b60bef5c504383afe0a6ff1c7984811 - had to make slight adjustments, because apparently the country code for Norway is `nl`, not `no`.
I've deployed it and you can test it at https://recalendar.me/create. Please feel free to open a new PR if you'd like to tweak the translation 🙇

**Comment by kwillno** [comment]
Ahh, sorry. The correct language code should be `nb` not `nl` which is for Dutch. There are some errors on the webpage now as automatic translations are in dutch while the rest are from my file.

**Comment by klimeryk** [comment]
@kwillno, yup, I've just realized my mistake! Sorry about that mixup! I'll fix it ASAP.

**Comment by klimeryk** [comment]
Sorry about that again, @kwillno. I've fixed the mistake in https://github.com/klimeryk/recalendar.js/commit/c108192d65bb9f2e29af5221627dcc4d97be4589 and deployed it. It should be 100% Norwegian now ;)

**Comment by kwillno** [comment]
No stress. Super cool project.
It is constant pain with two written languages :smile:

**Pull request closed without merging**
