### PR TITLE
feat: add pt-br translations

### PR DESCRIPTION
**Pull request by giovana-morais**
This PR adds Portuguese (pt-br) translation.

I left the [WIP] because I want to give it a second review tomorrow and maybe ask for a friend to review it too.

Thanks for the cool project!

### CODE REVIEW

**Comment by giovana-morais** [comment]
@klimeryk I have a question. when I try to use [`pt-br`](https://github.com/iamkun/dayjs/blob/dev/src/locale/pt-br.js) as the language code, following , the visualization breaks and I get this error:

> i18next::languageUtils: rejecting language code not found in supportedLngs: pt-BR

however when I use `pt` everything works normally. what do you think is the best? should we keep Brazilian Portuguese as `pt`?

**Comment by joaocrebelo** [comment]
@giovana-morais your proposal would work 100% for Portugal Portuguese (pt-pt) as well. In my opinion, it can be added as just "Portuguese" (or Português).

**Review by klimeryk — COMMENTED** [review]
@giovana-morais, thank you so much for taking the time to translate this to pt-BR 🙇‍♂️ Sorry for the slow follow-up.
I've taken your changes and made some adjustments to them so that `pt-BR` is recognized properly as the language code. Looks like you've uncovered an issue with this particular case:

i18next and dayjs expect different formats for codes like `pt-BR`:
 - i18next expects (and automatically corrects) `pt-BR`
 - dayjs expects `pt-br`

This difference in case is important as those strings are used for creating paths to files, so on most systems that's case-sensitive and one way or the other, it'd fail. So, to keep things simple and find a middle point, I've went with `pt-BR` and then lowercase it for dayjs use (which is easier than the other way around).

While @joaocrebelo mentions that it could be used for both `pt` and `pt-BR`, I want to be as precise as possible. For example, there could be differences in how dates are formatted, names of days of the week, months, etc. And, of course, other languages in this situation might have bigger differences.

Anyway, to make all of this work, I've taken your original commits, squashed them into one and then made some changes of mine. The result is https://github.com/klimeryk/recalendar.js/commit/caa5018249978dfabc910905770cf09e5fa31755 - we are both authors of it, so your contribution is definitely properly attributed 🙇‍♂️ 

Thanks again for the PR! I've left a note about two strings that stood out to me as not translated - feel free to open a new PR to have that corrected 🙇

**Comment by klimeryk** [comment]
Closing as changes have been merged as mentioned in https://github.com/klimeryk/recalendar.js/pull/39#pullrequestreview-1376943171 🙏

**Comment by giovana-morais** [comment]
hi @klimeryk and @joaocrebelo! thanks for taking some time to review, comment and fix the issue with the language code! for the missing translations, there is no actual missing translations. in Portuguese, "remove" is from the verb "remover". long story short, they are the same in Portuguese and English. (:

**Comment by klimeryk** [comment]
Hahaha, I did not know that and made assumptions! Sorry I doubted your translation then! 🙇

**Pull request closed without merging**
